''' <summary>
''' Deduplication of an element with a number of subscreens in the tabpage to
''' display the differences. This is the screen generated by Visual Studio
''' </summary>
<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Public Class FrmElementDeduplicator
	Inherits System.Windows.Forms.Form

    'Form overrides dispose to clean up the component list.
    <System.Diagnostics.DebuggerNonUserCode()>
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        Try
            If disposing AndAlso components IsNot Nothing Then
                components.Dispose()
            End If
        Finally
            MyBase.Dispose(disposing)
        End Try
    End Sub

    'Required by the Windows Form Designer
    Private components As System.ComponentModel.IContainer

    'NOTE: The following procedure is required by the Windows Form Designer
    'It can be modified using the Windows Form Designer.  
    'Do not modify it using the code editor.
    <System.Diagnostics.DebuggerStepThrough()>
    Private Sub InitializeComponent()
        Me.ButtonDeDuplicate = New System.Windows.Forms.Button()
        Me.Label5 = New System.Windows.Forms.Label()
        Me.ComboBoxElements = New System.Windows.Forms.ComboBox()
        Me.Label2 = New System.Windows.Forms.Label()
        Me.TabControlDuplicator = New System.Windows.Forms.TabControl()
        Me.TabPageObject = New System.Windows.Forms.TabPage()
        Me.SplitContainer5 = New System.Windows.Forms.SplitContainer()
        Me.OrigKeywords = New System.Windows.Forms.TextBox()
        Me.OrigAlias = New System.Windows.Forms.TextBox()
        Me.Label7 = New System.Windows.Forms.Label()
        Me.Label8 = New System.Windows.Forms.Label()
        Me.Label1 = New System.Windows.Forms.Label()
        Me.OrigNotes = New System.Windows.Forms.TextBox()
        Me.ButtonLoadGrid = New System.Windows.Forms.Button()
        Me.ButtonSplitOrientation = New System.Windows.Forms.Button()
        Me.ButtonAllMove = New System.Windows.Forms.Button()
        Me.ButtonNotesMove = New System.Windows.Forms.Button()
        Me.ButtonKeywordsMove = New System.Windows.Forms.Button()
        Me.ButtonAliasMove = New System.Windows.Forms.Button()
        Me.DuplKeywords = New System.Windows.Forms.TextBox()
        Me.DuplAlias = New System.Windows.Forms.TextBox()
        Me.Label6 = New System.Windows.Forms.Label()
        Me.Label4 = New System.Windows.Forms.Label()
        Me.DuplNotes = New System.Windows.Forms.TextBox()
        Me.Label3 = New System.Windows.Forms.Label()
        Me.TabPageAttributes = New System.Windows.Forms.TabPage()
        Me.SplitContainer1 = New System.Windows.Forms.SplitContainer()
        Me.DataGridViewAttrOriginal = New System.Windows.Forms.DataGridView()
        Me.DataGridViewAttrDuplicate = New System.Windows.Forms.DataGridView()
        Me.Splitter1 = New System.Windows.Forms.Splitter()
        Me.TabPageOperations = New System.Windows.Forms.TabPage()
        Me.SplitContainer2 = New System.Windows.Forms.SplitContainer()
        Me.DataGridViewOprOriginal = New System.Windows.Forms.DataGridView()
        Me.DataGridViewOprDuplicate = New System.Windows.Forms.DataGridView()
        Me.TabPageAssociations = New System.Windows.Forms.TabPage()
        Me.SplitContainer3 = New System.Windows.Forms.SplitContainer()
        Me.DataGridViewAssOriginal = New System.Windows.Forms.DataGridView()
        Me.DataGridViewAssDuplicate = New System.Windows.Forms.DataGridView()
        Me.TabPageTaggedValues = New System.Windows.Forms.TabPage()
        Me.SplitContainer4 = New System.Windows.Forms.SplitContainer()
        Me.DataGridViewTVOriginal = New System.Windows.Forms.DataGridView()
        Me.DataGridViewTVDuplicate = New System.Windows.Forms.DataGridView()
        Me.ButtonReloadOriginal = New System.Windows.Forms.Button()
        Me.Label10 = New System.Windows.Forms.Label()
        Me.TextBoxOriginalSearch = New System.Windows.Forms.TextBox()
        Me.ComboBoxOriginals = New System.Windows.Forms.ComboBox()
        Me.ButtonReloadDuplicate = New System.Windows.Forms.Button()
        Me.Label9 = New System.Windows.Forms.Label()
        Me.TextBoxDuplicateSearch = New System.Windows.Forms.TextBox()
        Me.CheckBoxDeleteDuplicate = New System.Windows.Forms.CheckBox()
        Me.LabelResult = New System.Windows.Forms.Label()
        Me.CheckBoxMerge = New System.Windows.Forms.CheckBox()
        Me.CheckBoxManualDeduplication = New System.Windows.Forms.CheckBox()
        Me.TabControlDuplicator.SuspendLayout()
        Me.TabPageObject.SuspendLayout()
        CType(Me.SplitContainer5, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.SplitContainer5.Panel1.SuspendLayout()
        Me.SplitContainer5.Panel2.SuspendLayout()
        Me.SplitContainer5.SuspendLayout()
        Me.TabPageAttributes.SuspendLayout()
        CType(Me.SplitContainer1, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.SplitContainer1.Panel1.SuspendLayout()
        Me.SplitContainer1.Panel2.SuspendLayout()
        Me.SplitContainer1.SuspendLayout()
        CType(Me.DataGridViewAttrOriginal, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.DataGridViewAttrDuplicate, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.TabPageOperations.SuspendLayout()
        CType(Me.SplitContainer2, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.SplitContainer2.Panel1.SuspendLayout()
        Me.SplitContainer2.Panel2.SuspendLayout()
        Me.SplitContainer2.SuspendLayout()
        CType(Me.DataGridViewOprOriginal, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.DataGridViewOprDuplicate, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.TabPageAssociations.SuspendLayout()
        CType(Me.SplitContainer3, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.SplitContainer3.Panel1.SuspendLayout()
        Me.SplitContainer3.Panel2.SuspendLayout()
        Me.SplitContainer3.SuspendLayout()
        CType(Me.DataGridViewAssOriginal, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.DataGridViewAssDuplicate, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.TabPageTaggedValues.SuspendLayout()
        CType(Me.SplitContainer4, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.SplitContainer4.Panel1.SuspendLayout()
        Me.SplitContainer4.Panel2.SuspendLayout()
        Me.SplitContainer4.SuspendLayout()
        CType(Me.DataGridViewTVOriginal, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.DataGridViewTVDuplicate, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.SuspendLayout()
        '
        'ButtonDeDuplicate
        '
        Me.ButtonDeDuplicate.Anchor = CType((System.Windows.Forms.AnchorStyles.Top Or System.Windows.Forms.AnchorStyles.Right), System.Windows.Forms.AnchorStyles)
        Me.ButtonDeDuplicate.BackColor = System.Drawing.Color.DimGray
        Me.ButtonDeDuplicate.FlatStyle = System.Windows.Forms.FlatStyle.System
        Me.ButtonDeDuplicate.Location = New System.Drawing.Point(712, 9)
        Me.ButtonDeDuplicate.Margin = New System.Windows.Forms.Padding(2)
        Me.ButtonDeDuplicate.Name = "ButtonDeDuplicate"
        Me.ButtonDeDuplicate.Size = New System.Drawing.Size(100, 30)
        Me.ButtonDeDuplicate.TabIndex = 19
        Me.ButtonDeDuplicate.Text = "Start Deduplicate"
        Me.ButtonDeDuplicate.UseVisualStyleBackColor = False
        '
        'Label5
        '
        Me.Label5.AutoSize = True
        Me.Label5.Location = New System.Drawing.Point(11, 77)
        Me.Label5.Margin = New System.Windows.Forms.Padding(2, 0, 2, 0)
        Me.Label5.Name = "Label5"
        Me.Label5.Size = New System.Drawing.Size(88, 13)
        Me.Label5.TabIndex = 18
        Me.Label5.Text = "Original Elements"
        '
        'ComboBoxElements
        '
        Me.ComboBoxElements.Anchor = CType((System.Windows.Forms.AnchorStyles.Top Or System.Windows.Forms.AnchorStyles.Right), System.Windows.Forms.AnchorStyles)
        Me.ComboBoxElements.FormattingEnabled = True
        Me.ComboBoxElements.Location = New System.Drawing.Point(543, 77)
        Me.ComboBoxElements.Margin = New System.Windows.Forms.Padding(2)
        Me.ComboBoxElements.Name = "ComboBoxElements"
        Me.ComboBoxElements.Size = New System.Drawing.Size(278, 21)
        Me.ComboBoxElements.TabIndex = 20
        '
        'Label2
        '
        Me.Label2.Anchor = CType((System.Windows.Forms.AnchorStyles.Top Or System.Windows.Forms.AnchorStyles.Right), System.Windows.Forms.AnchorStyles)
        Me.Label2.AutoSize = True
        Me.Label2.Location = New System.Drawing.Point(444, 80)
        Me.Label2.Margin = New System.Windows.Forms.Padding(2, 0, 2, 0)
        Me.Label2.Name = "Label2"
        Me.Label2.Size = New System.Drawing.Size(97, 13)
        Me.Label2.TabIndex = 22
        Me.Label2.Text = "Duplicate elements"
        '
        'TabControlDuplicator
        '
        Me.TabControlDuplicator.Anchor = CType((((System.Windows.Forms.AnchorStyles.Top Or System.Windows.Forms.AnchorStyles.Bottom) _
            Or System.Windows.Forms.AnchorStyles.Left) _
            Or System.Windows.Forms.AnchorStyles.Right), System.Windows.Forms.AnchorStyles)
        Me.TabControlDuplicator.Controls.Add(Me.TabPageObject)
        Me.TabControlDuplicator.Controls.Add(Me.TabPageAttributes)
        Me.TabControlDuplicator.Controls.Add(Me.TabPageOperations)
        Me.TabControlDuplicator.Controls.Add(Me.TabPageAssociations)
        Me.TabControlDuplicator.Controls.Add(Me.TabPageTaggedValues)
        Me.TabControlDuplicator.Location = New System.Drawing.Point(-4, 119)
        Me.TabControlDuplicator.Margin = New System.Windows.Forms.Padding(2)
        Me.TabControlDuplicator.Name = "TabControlDuplicator"
        Me.TabControlDuplicator.SelectedIndex = 0
        Me.TabControlDuplicator.Size = New System.Drawing.Size(826, 409)
        Me.TabControlDuplicator.TabIndex = 23
        '
        'TabPageObject
        '
        Me.TabPageObject.BackColor = System.Drawing.Color.LightGray
        Me.TabPageObject.Controls.Add(Me.SplitContainer5)
        Me.TabPageObject.Location = New System.Drawing.Point(4, 22)
        Me.TabPageObject.Margin = New System.Windows.Forms.Padding(2)
        Me.TabPageObject.Name = "TabPageObject"
        Me.TabPageObject.Padding = New System.Windows.Forms.Padding(2)
        Me.TabPageObject.Size = New System.Drawing.Size(818, 383)
        Me.TabPageObject.TabIndex = 3
        Me.TabPageObject.Text = "Object"
        '
        'SplitContainer5
        '
        Me.SplitContainer5.Dock = System.Windows.Forms.DockStyle.Fill
        Me.SplitContainer5.Location = New System.Drawing.Point(2, 2)
        Me.SplitContainer5.Margin = New System.Windows.Forms.Padding(2)
        Me.SplitContainer5.Name = "SplitContainer5"
        '
        'SplitContainer5.Panel1
        '
        Me.SplitContainer5.Panel1.BackColor = System.Drawing.Color.DarkGray
        Me.SplitContainer5.Panel1.Controls.Add(Me.OrigKeywords)
        Me.SplitContainer5.Panel1.Controls.Add(Me.OrigAlias)
        Me.SplitContainer5.Panel1.Controls.Add(Me.Label7)
        Me.SplitContainer5.Panel1.Controls.Add(Me.Label8)
        Me.SplitContainer5.Panel1.Controls.Add(Me.Label1)
        Me.SplitContainer5.Panel1.Controls.Add(Me.OrigNotes)
        Me.SplitContainer5.Panel1.Controls.Add(Me.ButtonLoadGrid)
        Me.SplitContainer5.Panel1.Controls.Add(Me.ButtonSplitOrientation)
        '
        'SplitContainer5.Panel2
        '
        Me.SplitContainer5.Panel2.BackColor = System.Drawing.Color.DarkGray
        Me.SplitContainer5.Panel2.Controls.Add(Me.ButtonAllMove)
        Me.SplitContainer5.Panel2.Controls.Add(Me.ButtonNotesMove)
        Me.SplitContainer5.Panel2.Controls.Add(Me.ButtonKeywordsMove)
        Me.SplitContainer5.Panel2.Controls.Add(Me.ButtonAliasMove)
        Me.SplitContainer5.Panel2.Controls.Add(Me.DuplKeywords)
        Me.SplitContainer5.Panel2.Controls.Add(Me.DuplAlias)
        Me.SplitContainer5.Panel2.Controls.Add(Me.Label6)
        Me.SplitContainer5.Panel2.Controls.Add(Me.Label4)
        Me.SplitContainer5.Panel2.Controls.Add(Me.DuplNotes)
        Me.SplitContainer5.Panel2.Controls.Add(Me.Label3)
        Me.SplitContainer5.Size = New System.Drawing.Size(814, 379)
        Me.SplitContainer5.SplitterDistance = 429
        Me.SplitContainer5.SplitterWidth = 3
        Me.SplitContainer5.TabIndex = 0
        '
        'OrigKeywords
        '
        Me.OrigKeywords.Anchor = CType(((System.Windows.Forms.AnchorStyles.Top Or System.Windows.Forms.AnchorStyles.Left) _
            Or System.Windows.Forms.AnchorStyles.Right), System.Windows.Forms.AnchorStyles)
        Me.OrigKeywords.Location = New System.Drawing.Point(4, 74)
        Me.OrigKeywords.Margin = New System.Windows.Forms.Padding(2)
        Me.OrigKeywords.Name = "OrigKeywords"
        Me.OrigKeywords.Size = New System.Drawing.Size(423, 20)
        Me.OrigKeywords.TabIndex = 12
        '
        'OrigAlias
        '
        Me.OrigAlias.Anchor = CType(((System.Windows.Forms.AnchorStyles.Top Or System.Windows.Forms.AnchorStyles.Left) _
            Or System.Windows.Forms.AnchorStyles.Right), System.Windows.Forms.AnchorStyles)
        Me.OrigAlias.Location = New System.Drawing.Point(4, 34)
        Me.OrigAlias.Margin = New System.Windows.Forms.Padding(2)
        Me.OrigAlias.Name = "OrigAlias"
        Me.OrigAlias.Size = New System.Drawing.Size(423, 20)
        Me.OrigAlias.TabIndex = 11
        '
        'Label7
        '
        Me.Label7.AutoSize = True
        Me.Label7.Location = New System.Drawing.Point(2, 57)
        Me.Label7.Margin = New System.Windows.Forms.Padding(2, 0, 2, 0)
        Me.Label7.Name = "Label7"
        Me.Label7.Size = New System.Drawing.Size(89, 13)
        Me.Label7.TabIndex = 10
        Me.Label7.Text = "Keywords original"
        '
        'Label8
        '
        Me.Label8.AutoSize = True
        Me.Label8.Location = New System.Drawing.Point(2, 16)
        Me.Label8.Margin = New System.Windows.Forms.Padding(2, 0, 2, 0)
        Me.Label8.Name = "Label8"
        Me.Label8.Size = New System.Drawing.Size(65, 13)
        Me.Label8.TabIndex = 9
        Me.Label8.Text = "Alias original"
        '
        'Label1
        '
        Me.Label1.AutoSize = True
        Me.Label1.Location = New System.Drawing.Point(2, 96)
        Me.Label1.Margin = New System.Windows.Forms.Padding(2, 0, 2, 0)
        Me.Label1.Name = "Label1"
        Me.Label1.Size = New System.Drawing.Size(71, 13)
        Me.Label1.TabIndex = 1
        Me.Label1.Text = "Notes original"
        '
        'OrigNotes
        '
        Me.OrigNotes.Anchor = CType((((System.Windows.Forms.AnchorStyles.Top Or System.Windows.Forms.AnchorStyles.Bottom) _
            Or System.Windows.Forms.AnchorStyles.Left) _
            Or System.Windows.Forms.AnchorStyles.Right), System.Windows.Forms.AnchorStyles)
        Me.OrigNotes.Location = New System.Drawing.Point(2, 111)
        Me.OrigNotes.Margin = New System.Windows.Forms.Padding(2)
        Me.OrigNotes.Multiline = True
        Me.OrigNotes.Name = "OrigNotes"
        Me.OrigNotes.ScrollBars = System.Windows.Forms.ScrollBars.Both
        Me.OrigNotes.Size = New System.Drawing.Size(427, 268)
        Me.OrigNotes.TabIndex = 0
        '
        'ButtonLoadGrid
        '
        Me.ButtonLoadGrid.Anchor = CType((System.Windows.Forms.AnchorStyles.Top Or System.Windows.Forms.AnchorStyles.Right), System.Windows.Forms.AnchorStyles)
        Me.ButtonLoadGrid.Location = New System.Drawing.Point(326, 3)
        Me.ButtonLoadGrid.Margin = New System.Windows.Forms.Padding(2)
        Me.ButtonLoadGrid.Name = "ButtonLoadGrid"
        Me.ButtonLoadGrid.Size = New System.Drawing.Size(100, 27)
        Me.ButtonLoadGrid.TabIndex = 24
        Me.ButtonLoadGrid.Text = "Load grids"
        Me.ButtonLoadGrid.UseVisualStyleBackColor = True
        '
        'ButtonSplitOrientation
        '
        Me.ButtonSplitOrientation.Anchor = CType((System.Windows.Forms.AnchorStyles.Top Or System.Windows.Forms.AnchorStyles.Right), System.Windows.Forms.AnchorStyles)
        Me.ButtonSplitOrientation.Location = New System.Drawing.Point(244, 3)
        Me.ButtonSplitOrientation.Name = "ButtonSplitOrientation"
        Me.ButtonSplitOrientation.Size = New System.Drawing.Size(75, 27)
        Me.ButtonSplitOrientation.TabIndex = 25
        Me.ButtonSplitOrientation.Text = "Orientation"
        Me.ButtonSplitOrientation.UseVisualStyleBackColor = True
        '
        'ButtonAllMove
        '
        Me.ButtonAllMove.Font = New System.Drawing.Font("Microsoft Sans Serif", 6.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.ButtonAllMove.Location = New System.Drawing.Point(5, 15)
        Me.ButtonAllMove.Margin = New System.Windows.Forms.Padding(0)
        Me.ButtonAllMove.Name = "ButtonAllMove"
        Me.ButtonAllMove.Size = New System.Drawing.Size(28, 24)
        Me.ButtonAllMove.TabIndex = 12
        Me.ButtonAllMove.Text = "<<"
        Me.ButtonAllMove.UseVisualStyleBackColor = True
        '
        'ButtonNotesMove
        '
        Me.ButtonNotesMove.Location = New System.Drawing.Point(4, 113)
        Me.ButtonNotesMove.Margin = New System.Windows.Forms.Padding(2)
        Me.ButtonNotesMove.Name = "ButtonNotesMove"
        Me.ButtonNotesMove.Size = New System.Drawing.Size(19, 23)
        Me.ButtonNotesMove.TabIndex = 11
        Me.ButtonNotesMove.Text = "<"
        Me.ButtonNotesMove.UseVisualStyleBackColor = True
        '
        'ButtonKeywordsMove
        '
        Me.ButtonKeywordsMove.Location = New System.Drawing.Point(5, 76)
        Me.ButtonKeywordsMove.Margin = New System.Windows.Forms.Padding(2)
        Me.ButtonKeywordsMove.Name = "ButtonKeywordsMove"
        Me.ButtonKeywordsMove.Size = New System.Drawing.Size(19, 24)
        Me.ButtonKeywordsMove.TabIndex = 10
        Me.ButtonKeywordsMove.Text = "<"
        Me.ButtonKeywordsMove.UseVisualStyleBackColor = True
        '
        'ButtonAliasMove
        '
        Me.ButtonAliasMove.Location = New System.Drawing.Point(5, 36)
        Me.ButtonAliasMove.Margin = New System.Windows.Forms.Padding(2)
        Me.ButtonAliasMove.Name = "ButtonAliasMove"
        Me.ButtonAliasMove.Size = New System.Drawing.Size(19, 24)
        Me.ButtonAliasMove.TabIndex = 9
        Me.ButtonAliasMove.Text = "<"
        Me.ButtonAliasMove.UseVisualStyleBackColor = True
        '
        'DuplKeywords
        '
        Me.DuplKeywords.Anchor = CType(((System.Windows.Forms.AnchorStyles.Top Or System.Windows.Forms.AnchorStyles.Left) _
            Or System.Windows.Forms.AnchorStyles.Right), System.Windows.Forms.AnchorStyles)
        Me.DuplKeywords.Location = New System.Drawing.Point(38, 74)
        Me.DuplKeywords.Margin = New System.Windows.Forms.Padding(2)
        Me.DuplKeywords.Name = "DuplKeywords"
        Me.DuplKeywords.Size = New System.Drawing.Size(346, 20)
        Me.DuplKeywords.TabIndex = 8
        '
        'DuplAlias
        '
        Me.DuplAlias.Anchor = CType(((System.Windows.Forms.AnchorStyles.Top Or System.Windows.Forms.AnchorStyles.Left) _
            Or System.Windows.Forms.AnchorStyles.Right), System.Windows.Forms.AnchorStyles)
        Me.DuplAlias.Location = New System.Drawing.Point(38, 34)
        Me.DuplAlias.Margin = New System.Windows.Forms.Padding(2)
        Me.DuplAlias.Name = "DuplAlias"
        Me.DuplAlias.Size = New System.Drawing.Size(346, 20)
        Me.DuplAlias.TabIndex = 7
        '
        'Label6
        '
        Me.Label6.AutoSize = True
        Me.Label6.Location = New System.Drawing.Point(36, 58)
        Me.Label6.Margin = New System.Windows.Forms.Padding(2, 0, 2, 0)
        Me.Label6.Name = "Label6"
        Me.Label6.Size = New System.Drawing.Size(99, 13)
        Me.Label6.TabIndex = 6
        Me.Label6.Text = "Keywords duplicate"
        '
        'Label4
        '
        Me.Label4.AutoSize = True
        Me.Label4.Location = New System.Drawing.Point(36, 16)
        Me.Label4.Margin = New System.Windows.Forms.Padding(2, 0, 2, 0)
        Me.Label4.Name = "Label4"
        Me.Label4.Size = New System.Drawing.Size(75, 13)
        Me.Label4.TabIndex = 5
        Me.Label4.Text = "Alias duplicate"
        '
        'DuplNotes
        '
        Me.DuplNotes.Anchor = CType((((System.Windows.Forms.AnchorStyles.Top Or System.Windows.Forms.AnchorStyles.Bottom) _
            Or System.Windows.Forms.AnchorStyles.Left) _
            Or System.Windows.Forms.AnchorStyles.Right), System.Windows.Forms.AnchorStyles)
        Me.DuplNotes.Location = New System.Drawing.Point(39, 111)
        Me.DuplNotes.Margin = New System.Windows.Forms.Padding(2)
        Me.DuplNotes.Multiline = True
        Me.DuplNotes.Name = "DuplNotes"
        Me.DuplNotes.ScrollBars = System.Windows.Forms.ScrollBars.Both
        Me.DuplNotes.Size = New System.Drawing.Size(346, 268)
        Me.DuplNotes.TabIndex = 4
        '
        'Label3
        '
        Me.Label3.AutoSize = True
        Me.Label3.Location = New System.Drawing.Point(36, 96)
        Me.Label3.Margin = New System.Windows.Forms.Padding(2, 0, 2, 0)
        Me.Label3.Name = "Label3"
        Me.Label3.Size = New System.Drawing.Size(81, 13)
        Me.Label3.TabIndex = 3
        Me.Label3.Text = "Notes duplicate"
        '
        'TabPageAttributes
        '
        Me.TabPageAttributes.BackColor = System.Drawing.Color.LightGray
        Me.TabPageAttributes.Controls.Add(Me.SplitContainer1)
        Me.TabPageAttributes.Controls.Add(Me.Splitter1)
        Me.TabPageAttributes.Location = New System.Drawing.Point(4, 22)
        Me.TabPageAttributes.Margin = New System.Windows.Forms.Padding(2)
        Me.TabPageAttributes.Name = "TabPageAttributes"
        Me.TabPageAttributes.Padding = New System.Windows.Forms.Padding(2)
        Me.TabPageAttributes.Size = New System.Drawing.Size(818, 383)
        Me.TabPageAttributes.TabIndex = 0
        Me.TabPageAttributes.Text = "Attributes"
        '
        'SplitContainer1
        '
        Me.SplitContainer1.Dock = System.Windows.Forms.DockStyle.Fill
        Me.SplitContainer1.Location = New System.Drawing.Point(4, 2)
        Me.SplitContainer1.Margin = New System.Windows.Forms.Padding(2)
        Me.SplitContainer1.Name = "SplitContainer1"
        '
        'SplitContainer1.Panel1
        '
        Me.SplitContainer1.Panel1.Controls.Add(Me.DataGridViewAttrOriginal)
        '
        'SplitContainer1.Panel2
        '
        Me.SplitContainer1.Panel2.Controls.Add(Me.DataGridViewAttrDuplicate)
        Me.SplitContainer1.Size = New System.Drawing.Size(812, 379)
        Me.SplitContainer1.SplitterDistance = 432
        Me.SplitContainer1.SplitterWidth = 3
        Me.SplitContainer1.TabIndex = 3
        '
        'DataGridViewAttrOriginal
        '
        Me.DataGridViewAttrOriginal.AllowUserToAddRows = False
        Me.DataGridViewAttrOriginal.AllowUserToDeleteRows = False
        Me.DataGridViewAttrOriginal.AllowUserToOrderColumns = True
        Me.DataGridViewAttrOriginal.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize
        Me.DataGridViewAttrOriginal.Dock = System.Windows.Forms.DockStyle.Fill
        Me.DataGridViewAttrOriginal.Location = New System.Drawing.Point(0, 0)
        Me.DataGridViewAttrOriginal.Margin = New System.Windows.Forms.Padding(2)
        Me.DataGridViewAttrOriginal.Name = "DataGridViewAttrOriginal"
        Me.DataGridViewAttrOriginal.RowHeadersWidth = 51
        Me.DataGridViewAttrOriginal.RowTemplate.Height = 24
        Me.DataGridViewAttrOriginal.Size = New System.Drawing.Size(432, 379)
        Me.DataGridViewAttrOriginal.TabIndex = 0
        '
        'DataGridViewAttrDuplicate
        '
        Me.DataGridViewAttrDuplicate.AllowUserToAddRows = False
        Me.DataGridViewAttrDuplicate.AllowUserToDeleteRows = False
        Me.DataGridViewAttrDuplicate.AllowUserToOrderColumns = True
        Me.DataGridViewAttrDuplicate.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize
        Me.DataGridViewAttrDuplicate.Dock = System.Windows.Forms.DockStyle.Fill
        Me.DataGridViewAttrDuplicate.Location = New System.Drawing.Point(0, 0)
        Me.DataGridViewAttrDuplicate.Margin = New System.Windows.Forms.Padding(2)
        Me.DataGridViewAttrDuplicate.Name = "DataGridViewAttrDuplicate"
        Me.DataGridViewAttrDuplicate.RowHeadersWidth = 51
        Me.DataGridViewAttrDuplicate.RowTemplate.Height = 24
        Me.DataGridViewAttrDuplicate.Size = New System.Drawing.Size(377, 379)
        Me.DataGridViewAttrDuplicate.TabIndex = 1
        '
        'Splitter1
        '
        Me.Splitter1.Location = New System.Drawing.Point(2, 2)
        Me.Splitter1.Margin = New System.Windows.Forms.Padding(2)
        Me.Splitter1.Name = "Splitter1"
        Me.Splitter1.Size = New System.Drawing.Size(2, 379)
        Me.Splitter1.TabIndex = 2
        Me.Splitter1.TabStop = False
        '
        'TabPageOperations
        '
        Me.TabPageOperations.BackColor = System.Drawing.Color.LightGray
        Me.TabPageOperations.Controls.Add(Me.SplitContainer2)
        Me.TabPageOperations.Location = New System.Drawing.Point(4, 22)
        Me.TabPageOperations.Margin = New System.Windows.Forms.Padding(2)
        Me.TabPageOperations.Name = "TabPageOperations"
        Me.TabPageOperations.Padding = New System.Windows.Forms.Padding(2)
        Me.TabPageOperations.Size = New System.Drawing.Size(818, 383)
        Me.TabPageOperations.TabIndex = 1
        Me.TabPageOperations.Text = "Operations"
        '
        'SplitContainer2
        '
        Me.SplitContainer2.Dock = System.Windows.Forms.DockStyle.Fill
        Me.SplitContainer2.Location = New System.Drawing.Point(2, 2)
        Me.SplitContainer2.Margin = New System.Windows.Forms.Padding(2)
        Me.SplitContainer2.Name = "SplitContainer2"
        '
        'SplitContainer2.Panel1
        '
        Me.SplitContainer2.Panel1.Controls.Add(Me.DataGridViewOprOriginal)
        '
        'SplitContainer2.Panel2
        '
        Me.SplitContainer2.Panel2.Controls.Add(Me.DataGridViewOprDuplicate)
        Me.SplitContainer2.Size = New System.Drawing.Size(814, 379)
        Me.SplitContainer2.SplitterDistance = 401
        Me.SplitContainer2.SplitterWidth = 3
        Me.SplitContainer2.TabIndex = 0
        '
        'DataGridViewOprOriginal
        '
        Me.DataGridViewOprOriginal.AllowUserToAddRows = False
        Me.DataGridViewOprOriginal.AllowUserToDeleteRows = False
        Me.DataGridViewOprOriginal.AllowUserToOrderColumns = True
        Me.DataGridViewOprOriginal.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize
        Me.DataGridViewOprOriginal.Dock = System.Windows.Forms.DockStyle.Fill
        Me.DataGridViewOprOriginal.Location = New System.Drawing.Point(0, 0)
        Me.DataGridViewOprOriginal.Margin = New System.Windows.Forms.Padding(2)
        Me.DataGridViewOprOriginal.Name = "DataGridViewOprOriginal"
        Me.DataGridViewOprOriginal.RowHeadersWidth = 51
        Me.DataGridViewOprOriginal.RowTemplate.Height = 24
        Me.DataGridViewOprOriginal.Size = New System.Drawing.Size(401, 379)
        Me.DataGridViewOprOriginal.TabIndex = 1
        '
        'DataGridViewOprDuplicate
        '
        Me.DataGridViewOprDuplicate.AllowUserToAddRows = False
        Me.DataGridViewOprDuplicate.AllowUserToDeleteRows = False
        Me.DataGridViewOprDuplicate.AllowUserToOrderColumns = True
        Me.DataGridViewOprDuplicate.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize
        Me.DataGridViewOprDuplicate.Dock = System.Windows.Forms.DockStyle.Fill
        Me.DataGridViewOprDuplicate.Location = New System.Drawing.Point(0, 0)
        Me.DataGridViewOprDuplicate.Margin = New System.Windows.Forms.Padding(2)
        Me.DataGridViewOprDuplicate.Name = "DataGridViewOprDuplicate"
        Me.DataGridViewOprDuplicate.RowHeadersWidth = 51
        Me.DataGridViewOprDuplicate.RowTemplate.Height = 24
        Me.DataGridViewOprDuplicate.Size = New System.Drawing.Size(410, 379)
        Me.DataGridViewOprDuplicate.TabIndex = 2
        '
        'TabPageAssociations
        '
        Me.TabPageAssociations.BackColor = System.Drawing.Color.LightGray
        Me.TabPageAssociations.Controls.Add(Me.SplitContainer3)
        Me.TabPageAssociations.Location = New System.Drawing.Point(4, 22)
        Me.TabPageAssociations.Margin = New System.Windows.Forms.Padding(2)
        Me.TabPageAssociations.Name = "TabPageAssociations"
        Me.TabPageAssociations.Padding = New System.Windows.Forms.Padding(2)
        Me.TabPageAssociations.Size = New System.Drawing.Size(818, 383)
        Me.TabPageAssociations.TabIndex = 2
        Me.TabPageAssociations.Text = "Associations"
        '
        'SplitContainer3
        '
        Me.SplitContainer3.Dock = System.Windows.Forms.DockStyle.Fill
        Me.SplitContainer3.Location = New System.Drawing.Point(2, 2)
        Me.SplitContainer3.Name = "SplitContainer3"
        '
        'SplitContainer3.Panel1
        '
        Me.SplitContainer3.Panel1.Controls.Add(Me.DataGridViewAssOriginal)
        '
        'SplitContainer3.Panel2
        '
        Me.SplitContainer3.Panel2.Controls.Add(Me.DataGridViewAssDuplicate)
        Me.SplitContainer3.Size = New System.Drawing.Size(814, 379)
        Me.SplitContainer3.SplitterDistance = 391
        Me.SplitContainer3.TabIndex = 0
        '
        'DataGridViewAssOriginal
        '
        Me.DataGridViewAssOriginal.AllowUserToAddRows = False
        Me.DataGridViewAssOriginal.AllowUserToDeleteRows = False
        Me.DataGridViewAssOriginal.AllowUserToOrderColumns = True
        Me.DataGridViewAssOriginal.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize
        Me.DataGridViewAssOriginal.Dock = System.Windows.Forms.DockStyle.Fill
        Me.DataGridViewAssOriginal.Location = New System.Drawing.Point(0, 0)
        Me.DataGridViewAssOriginal.Margin = New System.Windows.Forms.Padding(2)
        Me.DataGridViewAssOriginal.Name = "DataGridViewAssOriginal"
        Me.DataGridViewAssOriginal.RowHeadersWidth = 51
        Me.DataGridViewAssOriginal.RowTemplate.Height = 24
        Me.DataGridViewAssOriginal.Size = New System.Drawing.Size(391, 379)
        Me.DataGridViewAssOriginal.TabIndex = 2
        '
        'DataGridViewAssDuplicate
        '
        Me.DataGridViewAssDuplicate.AllowUserToAddRows = False
        Me.DataGridViewAssDuplicate.AllowUserToDeleteRows = False
        Me.DataGridViewAssDuplicate.AllowUserToOrderColumns = True
        Me.DataGridViewAssDuplicate.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize
        Me.DataGridViewAssDuplicate.Dock = System.Windows.Forms.DockStyle.Fill
        Me.DataGridViewAssDuplicate.Location = New System.Drawing.Point(0, 0)
        Me.DataGridViewAssDuplicate.Margin = New System.Windows.Forms.Padding(2)
        Me.DataGridViewAssDuplicate.Name = "DataGridViewAssDuplicate"
        Me.DataGridViewAssDuplicate.RowHeadersWidth = 51
        Me.DataGridViewAssDuplicate.RowTemplate.Height = 24
        Me.DataGridViewAssDuplicate.Size = New System.Drawing.Size(419, 379)
        Me.DataGridViewAssDuplicate.TabIndex = 2
        '
        'TabPageTaggedValues
        '
        Me.TabPageTaggedValues.Controls.Add(Me.SplitContainer4)
        Me.TabPageTaggedValues.Location = New System.Drawing.Point(4, 22)
        Me.TabPageTaggedValues.Margin = New System.Windows.Forms.Padding(2)
        Me.TabPageTaggedValues.Name = "TabPageTaggedValues"
        Me.TabPageTaggedValues.Padding = New System.Windows.Forms.Padding(2)
        Me.TabPageTaggedValues.Size = New System.Drawing.Size(818, 383)
        Me.TabPageTaggedValues.TabIndex = 4
        Me.TabPageTaggedValues.Text = "Tagged Values"
        Me.TabPageTaggedValues.UseVisualStyleBackColor = True
        '
        'SplitContainer4
        '
        Me.SplitContainer4.Dock = System.Windows.Forms.DockStyle.Fill
        Me.SplitContainer4.Location = New System.Drawing.Point(2, 2)
        Me.SplitContainer4.Name = "SplitContainer4"
        '
        'SplitContainer4.Panel1
        '
        Me.SplitContainer4.Panel1.Controls.Add(Me.DataGridViewTVOriginal)
        '
        'SplitContainer4.Panel2
        '
        Me.SplitContainer4.Panel2.Controls.Add(Me.DataGridViewTVDuplicate)
        Me.SplitContainer4.Size = New System.Drawing.Size(814, 379)
        Me.SplitContainer4.SplitterDistance = 391
        Me.SplitContainer4.TabIndex = 1
        '
        'DataGridViewTVOriginal
        '
        Me.DataGridViewTVOriginal.AllowUserToAddRows = False
        Me.DataGridViewTVOriginal.AllowUserToDeleteRows = False
        Me.DataGridViewTVOriginal.AllowUserToOrderColumns = True
        Me.DataGridViewTVOriginal.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize
        Me.DataGridViewTVOriginal.Dock = System.Windows.Forms.DockStyle.Fill
        Me.DataGridViewTVOriginal.Location = New System.Drawing.Point(0, 0)
        Me.DataGridViewTVOriginal.Margin = New System.Windows.Forms.Padding(2)
        Me.DataGridViewTVOriginal.Name = "DataGridViewTVOriginal"
        Me.DataGridViewTVOriginal.RowHeadersWidth = 51
        Me.DataGridViewTVOriginal.RowTemplate.Height = 24
        Me.DataGridViewTVOriginal.Size = New System.Drawing.Size(391, 379)
        Me.DataGridViewTVOriginal.TabIndex = 2
        '
        'DataGridViewTVDuplicate
        '
        Me.DataGridViewTVDuplicate.AllowUserToAddRows = False
        Me.DataGridViewTVDuplicate.AllowUserToDeleteRows = False
        Me.DataGridViewTVDuplicate.AllowUserToOrderColumns = True
        Me.DataGridViewTVDuplicate.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize
        Me.DataGridViewTVDuplicate.Dock = System.Windows.Forms.DockStyle.Fill
        Me.DataGridViewTVDuplicate.Location = New System.Drawing.Point(0, 0)
        Me.DataGridViewTVDuplicate.Margin = New System.Windows.Forms.Padding(2)
        Me.DataGridViewTVDuplicate.Name = "DataGridViewTVDuplicate"
        Me.DataGridViewTVDuplicate.RowHeadersWidth = 51
        Me.DataGridViewTVDuplicate.RowTemplate.Height = 24
        Me.DataGridViewTVDuplicate.Size = New System.Drawing.Size(419, 379)
        Me.DataGridViewTVDuplicate.TabIndex = 2
        '
        'ButtonReloadOriginal
        '
        Me.ButtonReloadOriginal.Location = New System.Drawing.Point(343, 50)
        Me.ButtonReloadOriginal.Name = "ButtonReloadOriginal"
        Me.ButtonReloadOriginal.Size = New System.Drawing.Size(73, 22)
        Me.ButtonReloadOriginal.TabIndex = 31
        Me.ButtonReloadOriginal.Text = "Reload"
        Me.ButtonReloadOriginal.UseVisualStyleBackColor = True
        '
        'Label10
        '
        Me.Label10.AutoSize = True
        Me.Label10.Location = New System.Drawing.Point(11, 50)
        Me.Label10.Name = "Label10"
        Me.Label10.Size = New System.Drawing.Size(77, 13)
        Me.Label10.TabIndex = 30
        Me.Label10.Text = "Original search"
        '
        'TextBoxOriginalSearch
        '
        Me.TextBoxOriginalSearch.Location = New System.Drawing.Point(108, 50)
        Me.TextBoxOriginalSearch.Name = "TextBoxOriginalSearch"
        Me.TextBoxOriginalSearch.Size = New System.Drawing.Size(229, 20)
        Me.TextBoxOriginalSearch.TabIndex = 27
        '
        'ComboBoxOriginals
        '
        Me.ComboBoxOriginals.FormattingEnabled = True
        Me.ComboBoxOriginals.Location = New System.Drawing.Point(108, 77)
        Me.ComboBoxOriginals.Margin = New System.Windows.Forms.Padding(2)
        Me.ComboBoxOriginals.Name = "ComboBoxOriginals"
        Me.ComboBoxOriginals.Size = New System.Drawing.Size(308, 21)
        Me.ComboBoxOriginals.TabIndex = 26
        '
        'ButtonReloadDuplicate
        '
        Me.ButtonReloadDuplicate.Anchor = CType((System.Windows.Forms.AnchorStyles.Top Or System.Windows.Forms.AnchorStyles.Right), System.Windows.Forms.AnchorStyles)
        Me.ButtonReloadDuplicate.Location = New System.Drawing.Point(744, 50)
        Me.ButtonReloadDuplicate.Name = "ButtonReloadDuplicate"
        Me.ButtonReloadDuplicate.Size = New System.Drawing.Size(73, 22)
        Me.ButtonReloadDuplicate.TabIndex = 32
        Me.ButtonReloadDuplicate.Text = "Reload"
        Me.ButtonReloadDuplicate.UseVisualStyleBackColor = True
        '
        'Label9
        '
        Me.Label9.Anchor = CType((System.Windows.Forms.AnchorStyles.Top Or System.Windows.Forms.AnchorStyles.Right), System.Windows.Forms.AnchorStyles)
        Me.Label9.AutoSize = True
        Me.Label9.Location = New System.Drawing.Point(445, 53)
        Me.Label9.Name = "Label9"
        Me.Label9.Size = New System.Drawing.Size(87, 13)
        Me.Label9.TabIndex = 29
        Me.Label9.Text = "Duplicate search"
        '
        'TextBoxDuplicateSearch
        '
        Me.TextBoxDuplicateSearch.Anchor = CType((System.Windows.Forms.AnchorStyles.Top Or System.Windows.Forms.AnchorStyles.Right), System.Windows.Forms.AnchorStyles)
        Me.TextBoxDuplicateSearch.Location = New System.Drawing.Point(543, 50)
        Me.TextBoxDuplicateSearch.Name = "TextBoxDuplicateSearch"
        Me.TextBoxDuplicateSearch.Size = New System.Drawing.Size(193, 20)
        Me.TextBoxDuplicateSearch.TabIndex = 28
        '
        'CheckBoxDeleteDuplicate
        '
        Me.CheckBoxDeleteDuplicate.Anchor = CType((System.Windows.Forms.AnchorStyles.Top Or System.Windows.Forms.AnchorStyles.Right), System.Windows.Forms.AnchorStyles)
        Me.CheckBoxDeleteDuplicate.AutoSize = True
        Me.CheckBoxDeleteDuplicate.Location = New System.Drawing.Point(412, 16)
        Me.CheckBoxDeleteDuplicate.Name = "CheckBoxDeleteDuplicate"
        Me.CheckBoxDeleteDuplicate.Size = New System.Drawing.Size(162, 17)
        Me.CheckBoxDeleteDuplicate.TabIndex = 27
        Me.CheckBoxDeleteDuplicate.Text = "Delete duplicate after routine"
        Me.CheckBoxDeleteDuplicate.UseVisualStyleBackColor = True
        '
        'LabelResult
        '
        Me.LabelResult.AutoSize = True
        Me.LabelResult.Location = New System.Drawing.Point(9, 119)
        Me.LabelResult.Margin = New System.Windows.Forms.Padding(2, 0, 2, 0)
        Me.LabelResult.Name = "LabelResult"
        Me.LabelResult.Size = New System.Drawing.Size(0, 13)
        Me.LabelResult.TabIndex = 28
        '
        'CheckBoxMerge
        '
        Me.CheckBoxMerge.Anchor = CType((System.Windows.Forms.AnchorStyles.Top Or System.Windows.Forms.AnchorStyles.Right), System.Windows.Forms.AnchorStyles)
        Me.CheckBoxMerge.AutoSize = True
        Me.CheckBoxMerge.Checked = True
        Me.CheckBoxMerge.CheckState = System.Windows.Forms.CheckState.Checked
        Me.CheckBoxMerge.Location = New System.Drawing.Point(264, 16)
        Me.CheckBoxMerge.Name = "CheckBoxMerge"
        Me.CheckBoxMerge.Size = New System.Drawing.Size(89, 17)
        Me.CheckBoxMerge.TabIndex = 29
        Me.CheckBoxMerge.Text = "Merge details"
        Me.CheckBoxMerge.UseVisualStyleBackColor = True
        '
        'CheckBoxManualDeduplication
        '
        Me.CheckBoxManualDeduplication.Anchor = CType((System.Windows.Forms.AnchorStyles.Top Or System.Windows.Forms.AnchorStyles.Right), System.Windows.Forms.AnchorStyles)
        Me.CheckBoxManualDeduplication.AutoSize = True
        Me.CheckBoxManualDeduplication.Location = New System.Drawing.Point(580, 16)
        Me.CheckBoxManualDeduplication.Name = "CheckBoxManualDeduplication"
        Me.CheckBoxManualDeduplication.Size = New System.Drawing.Size(127, 17)
        Me.CheckBoxManualDeduplication.TabIndex = 33
        Me.CheckBoxManualDeduplication.Text = "Manual deduplication"
        Me.CheckBoxManualDeduplication.UseVisualStyleBackColor = True
        '
        'FrmElementDeduplicator
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.ClientSize = New System.Drawing.Size(821, 520)
        Me.Controls.Add(Me.CheckBoxManualDeduplication)
        Me.Controls.Add(Me.ButtonReloadDuplicate)
        Me.Controls.Add(Me.ButtonReloadOriginal)
        Me.Controls.Add(Me.Label9)
        Me.Controls.Add(Me.TextBoxDuplicateSearch)
        Me.Controls.Add(Me.CheckBoxMerge)
        Me.Controls.Add(Me.Label10)
        Me.Controls.Add(Me.LabelResult)
        Me.Controls.Add(Me.TextBoxOriginalSearch)
        Me.Controls.Add(Me.CheckBoxDeleteDuplicate)
        Me.Controls.Add(Me.ButtonDeDuplicate)
        Me.Controls.Add(Me.ComboBoxOriginals)
        Me.Controls.Add(Me.ComboBoxElements)
        Me.Controls.Add(Me.Label2)
        Me.Controls.Add(Me.TabControlDuplicator)
        Me.Controls.Add(Me.Label5)
        Me.Margin = New System.Windows.Forms.Padding(2)
        Me.Name = "FrmElementDeduplicator"
        Me.Text = "Data Element Deduplicator"
        Me.TabControlDuplicator.ResumeLayout(False)
        Me.TabPageObject.ResumeLayout(False)
        Me.SplitContainer5.Panel1.ResumeLayout(False)
        Me.SplitContainer5.Panel1.PerformLayout()
        Me.SplitContainer5.Panel2.ResumeLayout(False)
        Me.SplitContainer5.Panel2.PerformLayout()
        CType(Me.SplitContainer5, System.ComponentModel.ISupportInitialize).EndInit()
        Me.SplitContainer5.ResumeLayout(False)
        Me.TabPageAttributes.ResumeLayout(False)
        Me.SplitContainer1.Panel1.ResumeLayout(False)
        Me.SplitContainer1.Panel2.ResumeLayout(False)
        CType(Me.SplitContainer1, System.ComponentModel.ISupportInitialize).EndInit()
        Me.SplitContainer1.ResumeLayout(False)
        CType(Me.DataGridViewAttrOriginal, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.DataGridViewAttrDuplicate, System.ComponentModel.ISupportInitialize).EndInit()
        Me.TabPageOperations.ResumeLayout(False)
        Me.SplitContainer2.Panel1.ResumeLayout(False)
        Me.SplitContainer2.Panel2.ResumeLayout(False)
        CType(Me.SplitContainer2, System.ComponentModel.ISupportInitialize).EndInit()
        Me.SplitContainer2.ResumeLayout(False)
        CType(Me.DataGridViewOprOriginal, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.DataGridViewOprDuplicate, System.ComponentModel.ISupportInitialize).EndInit()
        Me.TabPageAssociations.ResumeLayout(False)
        Me.SplitContainer3.Panel1.ResumeLayout(False)
        Me.SplitContainer3.Panel2.ResumeLayout(False)
        CType(Me.SplitContainer3, System.ComponentModel.ISupportInitialize).EndInit()
        Me.SplitContainer3.ResumeLayout(False)
        CType(Me.DataGridViewAssOriginal, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.DataGridViewAssDuplicate, System.ComponentModel.ISupportInitialize).EndInit()
        Me.TabPageTaggedValues.ResumeLayout(False)
        Me.SplitContainer4.Panel1.ResumeLayout(False)
        Me.SplitContainer4.Panel2.ResumeLayout(False)
        CType(Me.SplitContainer4, System.ComponentModel.ISupportInitialize).EndInit()
        Me.SplitContainer4.ResumeLayout(False)
        CType(Me.DataGridViewTVOriginal, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.DataGridViewTVDuplicate, System.ComponentModel.ISupportInitialize).EndInit()
        Me.ResumeLayout(False)
        Me.PerformLayout()

    End Sub

    Friend WithEvents ButtonDeDuplicate As System.Windows.Forms.Button
    Friend WithEvents Label5 As System.Windows.Forms.Label
    Friend WithEvents ComboBoxElements As System.Windows.Forms.ComboBox
    Friend WithEvents Label2 As System.Windows.Forms.Label
    Friend WithEvents TabControlDuplicator As System.Windows.Forms.TabControl
    Friend WithEvents TabPageAttributes As System.Windows.Forms.TabPage
    Friend WithEvents TabPageOperations As System.Windows.Forms.TabPage
    Friend WithEvents TabPageAssociations As System.Windows.Forms.TabPage
    Friend WithEvents TabPageObject As System.Windows.Forms.TabPage
    Friend WithEvents DataGridViewAttrDuplicate As System.Windows.Forms.DataGridView
    Friend WithEvents SplitContainer1 As System.Windows.Forms.SplitContainer
    Friend WithEvents DataGridViewAttrOriginal As System.Windows.Forms.DataGridView
    Friend WithEvents Splitter1 As System.Windows.Forms.Splitter
    Friend WithEvents ButtonLoadGrid As System.Windows.Forms.Button
    Friend WithEvents SplitContainer2 As System.Windows.Forms.SplitContainer
    Friend WithEvents DataGridViewOprOriginal As System.Windows.Forms.DataGridView
    Friend WithEvents DataGridViewOprDuplicate As System.Windows.Forms.DataGridView
    Friend WithEvents SplitContainer3 As System.Windows.Forms.SplitContainer
    Friend WithEvents DataGridViewAssOriginal As System.Windows.Forms.DataGridView
    Friend WithEvents DataGridViewAssDuplicate As System.Windows.Forms.DataGridView
    Friend WithEvents ButtonSplitOrientation As System.Windows.Forms.Button
    Friend WithEvents TabPageTaggedValues As System.Windows.Forms.TabPage
    Friend WithEvents SplitContainer4 As System.Windows.Forms.SplitContainer
    Friend WithEvents DataGridViewTVOriginal As System.Windows.Forms.DataGridView
    Friend WithEvents DataGridViewTVDuplicate As System.Windows.Forms.DataGridView
    Friend WithEvents SplitContainer5 As System.Windows.Forms.SplitContainer
    Friend WithEvents OrigKeywords As System.Windows.Forms.TextBox
    Friend WithEvents OrigAlias As System.Windows.Forms.TextBox
    Friend WithEvents Label7 As System.Windows.Forms.Label
    Friend WithEvents Label8 As System.Windows.Forms.Label
    Friend WithEvents Label1 As System.Windows.Forms.Label
    Friend WithEvents OrigNotes As System.Windows.Forms.TextBox
    Friend WithEvents DuplKeywords As System.Windows.Forms.TextBox
    Friend WithEvents DuplAlias As System.Windows.Forms.TextBox
    Friend WithEvents Label6 As System.Windows.Forms.Label
    Friend WithEvents Label4 As System.Windows.Forms.Label
    Friend WithEvents DuplNotes As System.Windows.Forms.TextBox
    Friend WithEvents Label3 As System.Windows.Forms.Label
    Friend WithEvents ButtonAllMove As System.Windows.Forms.Button
    Friend WithEvents ButtonNotesMove As System.Windows.Forms.Button
    Friend WithEvents ButtonKeywordsMove As System.Windows.Forms.Button
    Friend WithEvents ButtonAliasMove As System.Windows.Forms.Button
    Friend WithEvents ComboBoxOriginals As System.Windows.Forms.ComboBox
    Friend WithEvents CheckBoxDeleteDuplicate As System.Windows.Forms.CheckBox
    Friend WithEvents LabelResult As System.Windows.Forms.Label
    Friend WithEvents ButtonReloadOriginal As System.Windows.Forms.Button
    Friend WithEvents Label10 As System.Windows.Forms.Label
    Friend WithEvents TextBoxOriginalSearch As System.Windows.Forms.TextBox
    Friend WithEvents ButtonReloadDuplicate As System.Windows.Forms.Button
    Friend WithEvents Label9 As System.Windows.Forms.Label
    Friend WithEvents TextBoxDuplicateSearch As System.Windows.Forms.TextBox
    Friend WithEvents CheckBoxMerge As System.Windows.Forms.CheckBox
    Friend WithEvents CheckBoxManualDeduplication As System.Windows.Forms.CheckBox
End Class
