''' <summary>
''' Welcome screen of the IDEA AddOn, code generated by Visual Studio
''' </summary>
<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Public Class WndWelcome
	Inherits System.Windows.Forms.Form

    'Form overrides dispose to clean up the component list.
    <System.Diagnostics.DebuggerNonUserCode()> _
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        Try
            If disposing AndAlso components IsNot Nothing Then
                components.Dispose()
            End If
        Finally
            MyBase.Dispose(disposing)
        End Try
    End Sub

    'Required by the Windows Form Designer
    Private components As System.ComponentModel.IContainer

    'NOTE: The following procedure is required by the Windows Form Designer
    'It can be modified using the Windows Form Designer.  
    'Do not modify it using the code editor.
    <System.Diagnostics.DebuggerStepThrough()> _
    Private Sub InitializeComponent()
        Me.Label1 = New System.Windows.Forms.Label()
        Me.TextBox1 = New System.Windows.Forms.TextBox()
        Me.ButtonArchiAid = New System.Windows.Forms.Button()
        Me.ButtonReleaseManager = New System.Windows.Forms.Button()
        Me.ButtonExcelImporter = New System.Windows.Forms.Button()
        Me.ButtonSimpleQuery = New System.Windows.Forms.Button()
        Me.ButtonFrmDataVault = New System.Windows.Forms.Button()
        Me.Button1 = New System.Windows.Forms.Button()
        Me.ButtonSettings = New System.Windows.Forms.Button()
        Me.TextBoxVersion = New System.Windows.Forms.TextBox()
        Me.SuspendLayout()
        '
        'Label1
        '
        Me.Label1.AutoSize = True
        Me.Label1.Font = New System.Drawing.Font("Microsoft Sans Serif", 10.0!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.Label1.Location = New System.Drawing.Point(12, 9)
        Me.Label1.Name = "Label1"
        Me.Label1.Size = New System.Drawing.Size(380, 17)
        Me.Label1.TabIndex = 1
        Me.Label1.Text = "IDEA and TEA addon for Sparx Enterprise Architect"
        '
        'TextBox1
        '
        Me.TextBox1.BackColor = System.Drawing.Color.FromArgb(CType(CType(255, Byte), Integer), CType(CType(255, Byte), Integer), CType(CType(192, Byte), Integer))
        Me.TextBox1.Location = New System.Drawing.Point(15, 167)
        Me.TextBox1.Multiline = True
        Me.TextBox1.Name = "TextBox1"
        Me.TextBox1.ReadOnly = True
        Me.TextBox1.Size = New System.Drawing.Size(476, 55)
        Me.TextBox1.TabIndex = 2
        Me.TextBox1.TabStop = False
        Me.TextBox1.Text = "This AddOn is developed by Eaxpertise. " & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "More information and download: http://ea" &
    "xpertise.nl/ideaen.aspx" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "Developed by Bert Dingemans"
        Me.TextBox1.TextAlign = System.Windows.Forms.HorizontalAlignment.Center
        '
        'ButtonArchiAid
        '
        Me.ButtonArchiAid.Location = New System.Drawing.Point(15, 274)
        Me.ButtonArchiAid.Margin = New System.Windows.Forms.Padding(2, 2, 2, 2)
        Me.ButtonArchiAid.Name = "ButtonArchiAid"
        Me.ButtonArchiAid.Size = New System.Drawing.Size(81, 51)
        Me.ButtonArchiAid.TabIndex = 3
        Me.ButtonArchiAid.Text = "ArchimAid"
        Me.ButtonArchiAid.UseVisualStyleBackColor = True
        '
        'ButtonReleaseManager
        '
        Me.ButtonReleaseManager.Location = New System.Drawing.Point(211, 274)
        Me.ButtonReleaseManager.Margin = New System.Windows.Forms.Padding(2, 2, 2, 2)
        Me.ButtonReleaseManager.Name = "ButtonReleaseManager"
        Me.ButtonReleaseManager.Size = New System.Drawing.Size(81, 51)
        Me.ButtonReleaseManager.TabIndex = 4
        Me.ButtonReleaseManager.Text = "Release manager"
        Me.ButtonReleaseManager.UseVisualStyleBackColor = True
        '
        'ButtonExcelImporter
        '
        Me.ButtonExcelImporter.Location = New System.Drawing.Point(309, 274)
        Me.ButtonExcelImporter.Margin = New System.Windows.Forms.Padding(2, 2, 2, 2)
        Me.ButtonExcelImporter.Name = "ButtonExcelImporter"
        Me.ButtonExcelImporter.Size = New System.Drawing.Size(81, 51)
        Me.ButtonExcelImporter.TabIndex = 5
        Me.ButtonExcelImporter.Text = "Excel importer"
        Me.ButtonExcelImporter.UseVisualStyleBackColor = True
        '
        'ButtonSimpleQuery
        '
        Me.ButtonSimpleQuery.Location = New System.Drawing.Point(408, 304)
        Me.ButtonSimpleQuery.Margin = New System.Windows.Forms.Padding(2, 2, 2, 2)
        Me.ButtonSimpleQuery.Name = "ButtonSimpleQuery"
        Me.ButtonSimpleQuery.Size = New System.Drawing.Size(83, 22)
        Me.ButtonSimpleQuery.TabIndex = 9
        Me.ButtonSimpleQuery.Text = "Simple query"
        Me.ButtonSimpleQuery.UseVisualStyleBackColor = True
        '
        'ButtonFrmDataVault
        '
        Me.ButtonFrmDataVault.Location = New System.Drawing.Point(113, 274)
        Me.ButtonFrmDataVault.Margin = New System.Windows.Forms.Padding(2, 2, 2, 2)
        Me.ButtonFrmDataVault.Name = "ButtonFrmDataVault"
        Me.ButtonFrmDataVault.Size = New System.Drawing.Size(81, 51)
        Me.ButtonFrmDataVault.TabIndex = 10
        Me.ButtonFrmDataVault.Text = "No Data Fault"
        Me.ButtonFrmDataVault.UseVisualStyleBackColor = True
        '
        'Button1
        '
        Me.Button1.BackColor = System.Drawing.SystemColors.Window
        Me.Button1.Image = Global.TEA.My.Resources.Resources.Eaxpertise_small
        Me.Button1.Location = New System.Drawing.Point(15, 28)
        Me.Button1.Margin = New System.Windows.Forms.Padding(2, 2, 2, 2)
        Me.Button1.Name = "Button1"
        Me.Button1.Size = New System.Drawing.Size(477, 134)
        Me.Button1.TabIndex = 6
        Me.Button1.UseVisualStyleBackColor = False
        '
        'ButtonSettings
        '
        Me.ButtonSettings.Location = New System.Drawing.Point(407, 273)
        Me.ButtonSettings.Margin = New System.Windows.Forms.Padding(2, 2, 2, 2)
        Me.ButtonSettings.Name = "ButtonSettings"
        Me.ButtonSettings.Size = New System.Drawing.Size(81, 22)
        Me.ButtonSettings.TabIndex = 11
        Me.ButtonSettings.Text = "Settings"
        Me.ButtonSettings.UseVisualStyleBackColor = True
        '
        'TextBoxVersion
        '
        Me.TextBoxVersion.BackColor = System.Drawing.Color.Lavender
        Me.TextBoxVersion.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle
        Me.TextBoxVersion.Enabled = False
        Me.TextBoxVersion.Location = New System.Drawing.Point(17, 235)
        Me.TextBoxVersion.Name = "TextBoxVersion"
        Me.TextBoxVersion.Size = New System.Drawing.Size(474, 20)
        Me.TextBoxVersion.TabIndex = 12
        Me.TextBoxVersion.TabStop = False
        Me.TextBoxVersion.TextAlign = System.Windows.Forms.HorizontalAlignment.Center
        '
        'WndWelcome
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.ClientSize = New System.Drawing.Size(503, 336)
        Me.Controls.Add(Me.TextBoxVersion)
        Me.Controls.Add(Me.ButtonSettings)
        Me.Controls.Add(Me.ButtonFrmDataVault)
        Me.Controls.Add(Me.ButtonSimpleQuery)
        Me.Controls.Add(Me.Button1)
        Me.Controls.Add(Me.ButtonExcelImporter)
        Me.Controls.Add(Me.ButtonReleaseManager)
        Me.Controls.Add(Me.ButtonArchiAid)
        Me.Controls.Add(Me.TextBox1)
        Me.Controls.Add(Me.Label1)
        Me.Margin = New System.Windows.Forms.Padding(2, 2, 2, 2)
        Me.Name = "WndWelcome"
        Me.Text = "Welcome to IDEA and TEA"
        Me.ResumeLayout(False)
        Me.PerformLayout()

    End Sub
    Friend WithEvents Label1 As System.Windows.Forms.Label
    Friend WithEvents TextBox1 As System.Windows.Forms.TextBox
    Friend WithEvents ButtonArchiAid As System.Windows.Forms.Button
    Friend WithEvents ButtonReleaseManager As System.Windows.Forms.Button
    Friend WithEvents ButtonExcelImporter As System.Windows.Forms.Button
    Friend WithEvents Button1 As System.Windows.Forms.Button
    Friend WithEvents ButtonSimpleQuery As System.Windows.Forms.Button
    Friend WithEvents ButtonFrmDataVault As System.Windows.Forms.Button
    Friend WithEvents ButtonSettings As System.Windows.Forms.Button
    Friend WithEvents TextBoxVersion As System.Windows.Forms.TextBox
End Class
